// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjlbhoyxsdidzqbubquf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqbGJob3l4c2RpZHpxYnVicXVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2MTMwNTYsImV4cCI6MjA1MTE4OTA1Nn0._X2BLhFicb_BfRPi7HwJmnZOn0aYgEi2q0T_g3kYiNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);